### ISSUE TITLE
Crash when running Genymotion

### ISSUE THREAD

**Issue by Qw4z1** [tvbarthel/BlurDialogFragment#2]
Hi,

The lib causes a force close when running it on Genymotion with Nexus 10-4.4.2-API 9-2560x1600-image. It works fine on a Nexus 4 and Nexus 7. 
Full stacktrace below:

```
11-04 07:57:09.494    1452-1521/se.textalk.media.reader.debug E/AndroidRuntime﹕ FATAL    EXCEPTION: AsyncTask #1
 Process: se.textalk.media.reader.debug, PID: 1452
java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=12544; index=12566
        at fr.tvbarthel.lib.blurdialogfragment.FastBlurHelper.doBlur(FastBlurHelper.java:127)
        at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine.blur(BlurDialogEngine.java:267)
        at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine.access$100(BlurDialogEngine.java:31)
        at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine$BlurAsyncTask.doInBackground(BlurDialogEngine.java:373)
        at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine$BlurAsyncTask.doInBackground(BlurDialogEngine.java:329)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
```

**Comment by Anth06ny** [comment]
+1

**Comment by kmayoral** [comment]
+1 I was able to reproduce on one of my Genymotion simulators. It worked well when testing on 
Genymotion Google Nexus - 5.0.0 - API 21 
Genymotion Motorola Droid Razr - 4.1.1 - API 16

but came across this error when testing with
Genymotion Samsung Galaxy S4 - 4.4.4 - API 19

Thanks for a cool library!

**Comment by ligol** [comment]
After some test, it work fine with Renderscript.
