### ISSUE TITLE
NPE at BlurDialogEngine#blur() during doInBackground

### ISSUE THREAD

**Issue by vbarthel-fr** [tvbarthel/BlurDialogFragment#3]
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:838)
Caused by: java.lang.NullPointerException
at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine.blur(BlurDialogEngine.java:273)
at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine.access$100(BlurDialogEngine.java:30)
at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine$BlurAsyncTask.doInBackground(BlurDialogEngine.java:353)
at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine$BlurAsyncTask.doInBackground(BlurDialogEngine.java:309)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
... 4 more

**Comment by jacobtabak** [comment]
Confirming this - `mBackground` can be `null` in `doInBackground()`.  I would suggest you use the other method of rendering the background view to canvas, i.e.

```
mBackground = new Bitmap(mBackgroundView.getWidth(), mBackgroundView.getHeight(), Bitmap.Config.ARGB_8888);
mBackgroundView.draw(mBackground);
```

**Comment by tbarthel-fr** [comment]
Hi @jacobtabak 

I'm so sorry for this late answer, kinda hard to find the time to work on side project :(

Have you any idea of how can I reproduce this NPE ?

I would use what you actually suggested but I have to find how to use a subset of src bitmap.

**Comment by serega2593** [comment]
Hi @tbarthel-fr 

You can reproduce this issue, if you programmatically call dialog.dismiss () immediately after dialog.show().

**Comment by tbarthel-fr** [comment]
Hi @serega2593 

I think I found what could lead to this NPE.

First of all, canceling an AsyncTask doesn't interupt the doInBackground, that's the reason why the javadoc warns to check isCancelled "periodically from doInBackground(Object[]) to finish the task as early as possible".

Then, the AsyncTask was only cancelled in the onDismiss() which isn't enough. In fact, I look deeper into the dimiss method of the DialogFragment and it call a dismissInternal method : 

```java
void dismissInternal(boolean allowStateLoss) {
        if (mDismissed) {
            return;
        }
        mDismissed = true;
        mShownByMe = false;
        if (mDialog != null) {
            mDialog.dismiss();
            mDialog = null;
        }
        mViewDestroyed = true;
        if (mBackStackId >= 0) {
            getFragmentManager().popBackStack(mBackStackId,
                    FragmentManager.POP_BACK_STACK_INCLUSIVE);
            mBackStackId = -1;
        } else {
            FragmentTransaction ft = getFragmentManager().beginTransaction();
            ft.remove(this);
            if (allowStateLoss) {
                ft.commitAllowingStateLoss();
            } else {
                ft.commit();
            }
        }
    }
```

If the dialog isn't yet instantiated, the Dialog.dismiss as well as DialogFragment.onDimiss(Dialog)  won't be called, which leads to a NPE.

Both corrections have been added to the 2.1.4 release d5f80565724828e41a1caa7c60a4f4340e0797ad which has already been uploaded on jCenter. 

Stay me tunned if this issue can be closed or if some unexpected behavior still persist :x 

I'm really sorry to haven't fixed that earlier...

Thanks a lot for your reports!

**Comment by serega2593** [comment]
Hi @tbarthel-fr 
I am glad to help you. I tested new version, not found this crash. I think you fixed it and you can close.
