### ISSUE TITLE
Crash when using in api 19 and appcompat v21.1

### ISSUE THREAD

**Issue by cgomezmendez** [tvbarthel/BlurDialogFragment#32]
It crash when I use it with android api 19, but when I try in 21 and up it doesn't:

update: also it's to note that we are using compat compat v21.1 before that, was working just fine.
<pre>
05-15 16:08:01.862 31662-31761/com.bebler.app E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #2
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:849)
Caused by: java.lang.VerifyError: fr/tvbarthel/lib/blurdialogfragment/FastBlurHelper
at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine.blur(BlurDialogEngine.java:389)
at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine.access$300(BlurDialogEngine.java:41)
at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine$BlurAsyncTask.doInBackground(BlurDialogEngine.java:564)
at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine$BlurAsyncTask.doInBackground(BlurDialogEngine.java:520)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:849)
</pre>

**Comment by tbarthel-fr** [comment]
Hi @cgomezmendez  (:

Thanks a lot for your report.

Which version of the library are you using ?

This error was known on the 2.1.1 version and shoud have been fixed in the 2.1.2 one : ef21d08e98355f74ea7948ab8a402185e2ca95e1
The VerifyError was linked to RenderScript v7 import in the FastBlurHelper.
The old fix was to add the following lines to your build.gradle even if you're not planning to use renderscript: 
defaultConfig {
        ...        
        renderscriptTargetApi 22
        renderscriptSupportModeEnabled true
        ...
}

I recommend you to use the last version promoted on jcCenter() : 
 compile 'fr.tvbarthel.blurdialogfragment:lib:2.1.2'

Tell us it solves your issue (:

Happy coding,

Thomas.
