### ISSUE TITLE
Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by Nook2007** [tvbarthel/BlurDialogFragment#39]
```java
java.lang.RuntimeException: Unable to destroy activity {simplecode.kz.megacam/simplecode.kz.megacam.module.player.PlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine$BlurAsyncTask.cancel(boolean)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4045)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4063)
       at android.app.ActivityThread.access$1400(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1413)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5696)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine$BlurAsyncTask.cancel(boolean)' on a null object reference
       at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine.onDestroy(BlurDialogEngine.java:199)
       at fr.tvbarthel.lib.blurdialogfragment.BlurDialogFragment.onDestroy(BlurDialogFragment.java:102)
       at android.app.Fragment.performDestroy(Fragment.java:2362)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1065)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1097)
       at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2055)
       at android.app.Activity.performDestroy(Activity.java:6136)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1169)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4025)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4063)
       at android.app.ActivityThread.access$1400(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1413)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5696)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
       ```

**Comment by tommytcchan** [comment]
I get this as well

**Comment by tbarthel-fr** [comment]
Hi @tommytcchan (:

Are this 20% linked to a specific use case or does it happen on a simple dialog dismiss ?

**Comment by tommytcchan** [comment]
I'd say it's random. I have a pr to address the issue, doesn't happen after
I put in the fix.
