### ISSUE TITLE
Runtime Error for `onDismiss` Listener 

### ISSUE THREAD

**Issue by kooroshh** [tvbarthel/BlurDialogFragment#59]
`05-03 19:44:23.328 30512-30512/net.test.xxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: net.test.xxx , PID: 30512
                                                                      java.lang.NullPointerException
                                                                          at android.app.DialogFragment.dismissInternal(DialogFragment.java:287)
                                                                          at android.app.DialogFragment.onDismiss(DialogFragment.java:452)
                                                                          at fr.tvbarthel.lib.blurdialogfragment.BlurDialogFragment.onDismiss(BlurDialogFragment.java:95)
                                                                          at net.test.xxx.Login$1.onClick(Login.java:61)
                                                                          at android.view.View.performClick(View.java:4438)
                                                                          at android.view.View$PerformClick.run(View.java:18422)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                          at dalvik.system.NativeStart.main(Native Method)`
everything works fine without listener .

**Comment by tbarthel-fr** [comment]
Hi @kooroshh (=

Could you give us more information on how you add your dismiss listener?

Here is a working example of how catch dialog dismiss events through a custom callback : 8c418a02867ce6d744b1f6b6f8132d245d82c54f

**Comment by tbarthel-fr** [comment]
Hi @kooroshh (:
Any update on your callback issue? may I close it?
