### ISSUE TITLE
NPE press back button on BlurDialogFragment

### ISSUE THREAD

**Issue by sekomod** [tvbarthel/BlurDialogFragment#62]
NPE press back button when MyDialogFragment which extends from BlurDialogFragment  is open
BlurDialogFragment Library Version is 2.1.6
About My Project    
        compileSdkVersion 23
        buildToolsVersion "23.0.3"
        minSdkVersion 15
        targetSdkVersion 23
 
Process: my.packagenamexxx, PID: 21110
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
                                                                    at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine$1.onPreDraw(BlurDialogEngine.java:170)
                                                                    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:921)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2164)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by markmooibroek** [comment]
I also have this issue (sometimes) when opening a BlurFragment. 

compileSdkVersion 24
buildToolsVersion "24.0.0"

minSdkVersion 16
targetSdkVersion 24

renderscriptTargetApi 22
renderscriptSupportModeEnabled true

**Comment by tbarthel-fr** [comment]
Hi @sekomod , hi @markmooibroek (=

Thanks a lot for the report. You can blame me for this issue, that's what happens when you try to maintain open source project without enough time :x 

We fixed this today #65 and a new version of the library is live on maven central: 
```java
     compile 'fr.tvbarthel.blurdialogfragment:lib:2.2.0'
```

One more time thanks a lot for your report!

Thomas.
